### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by wagger301** [OpenGeoscience/geonotebook#118]
The annotations buttons don't seem to be working. The cursor never changes to +.

**Comment by aashish24** [comment]
thanks for reporting the bug @wagger301 are you using the master?

**Comment by aashish24** [comment]
@jbeezley any chance you could look into it?

**Comment by jbeezley** [comment]
It works for me on our latest docker image.  `docker run -p 8888:8888 -v $PWD/notebooks:/notebooks geonotebook/geonotebook`  What browser are you running?

**Comment by wagger301** [comment]
I've tried firefox and chrome. I pulled last night and built the docker. The buttons don't even show up in Safari.

Thanks

**Comment by jbeezley** [comment]
I built a new image just now and the annotations worked correctly in Chrome, Firefox, and Safari.  Are you getting any console error messages?  What happens if you pull our prebuilt image from docker hub (`geonotebook/geonotebook`)?

**Comment by wagger301** [comment]
The image from docker hub works. Thanks!
