### ISSUE TITLE
/bin/sh: 1: girder-cli: not found on macOs

### ISSUE THREAD

**Issue by dementiev** [OpenGeoscience/geonotebook#145]
girder-client was installed via pip additionally.
When I try to run the command from 3rd demo https://github.com/OpenGeoscience/geonotebook/blob/master/notebooks/03_Time_Series.ipynb - i receive such an error:
`/bin/sh: 1: girder-cli: not found
`
```
which girder-cli
/usr/local/bin/girder-cli
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Any suggests on how to to run girder-cli?

MacOs Sierra 10.12.6.

**Comment by kotfic** [comment]
@dementiev [girder-cli](http://girder.readthedocs.io/en/latest/python-client.html) is a pip installable package,  you should be able to run ```pip install girder-cli```

**Comment by dementiev** [comment]
@kotfic i made it (stated in issue description), still doesnt work for me.

**Comment by dementiev** [comment]
Additional info: from command line this command works
`girder-cli --api-url https://data.kitware.com/api/v1 localsync 58dd35fd8d777f0aef5d8c73 data`
If I run it from notebook: 
```
  File "<ipython-input-36-8b449d93602e>", line 1
    girder-cli --api-url https://data.kitware.com/api/v1 localsync 58dd35fd8d777f0aef5d8c73 data
                             ^
SyntaxError: invalid syntax
```

**Comment by danlamanna** [comment]
In the notebook, are you prefixing the girder-cli command with an
exclamation point like so:
!girder-cli --api-url https://data.kitware.com/api/v1 localsync
58dd35fd8d777f0aef5d8c73 data

That lets the notebook know that it needs to execute it outside of
Python (in the shell).

**Comment by dementiev** [comment]
@danlamanna if I do it with exclamation sign, I receive initial error:
`/bin/sh: 1: girder-cli: not found
`

**Comment by danlamanna** [comment]
Does it happen if you replace girder-cli with /usr/local/bin/girder-cli ?

**Comment by dementiev** [comment]
yes, the same error
`/bin/sh: 1: /usr/local/bin/girder-cli: not found
`

**Comment by danlamanna** [comment]
Are you using the Docker installation of GeoNotebook? It seems like the
filesystem you installed girder-cli on is not the same as the one you're
running the notebook on.

One way to work around this is to use the notebook to pip install
girder-cli (prefixing with the exclamation point again).

**Comment by dementiev** [comment]
I use the same file system, installed everything with docker on my mac. 
`!pip install girder-cli `in notebook returns to me
```
Collecting girder-cli
  Could not find a version that satisfies the requirement girder-cli (from versions: )
No matching distribution found for girder-cli
```

**Comment by dementiev** [comment]
With more logs: 
!pip install -vvv girder-cli 
```
Collecting girder-cli
  1 location(s) to search for versions of girder-cli:
  * https://pypi.python.org/simple/girder-cli/
  Getting page https://pypi.python.org/simple/girder-cli/
  Looking up "https://pypi.python.org/simple/girder-cli/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/girder-cli/ HTTP/1.1" 404 39
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/girder-cli/: 404 Client Error: Not Found (girder-cli does not exist) for url: https://pypi.python.org/simple/girder-cli/ - skipping
  Could not find a version that satisfies the requirement girder-cli (from versions: )
Cleaning up...
No matching distribution found for girder-cli
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python2.7/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for girder-cli
```

**Comment by danlamanna** [comment]
Sorry, `girder-client` instead of `girder-cli`.

**Comment by dementiev** [comment]
@danlamanna thank you so much, now girder-cli runs without any errors.
