### ISSUE TITLE
M.layers.annotation.polygons[0].data - IndexError: list index out of range

### ISSUE THREAD

**Issue by dementiev** [OpenGeoscience/geonotebook#147]
When I run 3rd cell from 

https://github.com/OpenGeoscience/geonotebook/blob/master/notebooks/04_Annotations.ipynb

d, n = next(M.layers.annotation.polygons[0].data)

I receive:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-11-66a9995560d8> in <module>()
----> 1 d, n = next(M.layers.annotation.polygons[0].data)
      2 #d, n = next(M.layers.annotation.rectangles[1].data)

IndexError: list index out of range

**Comment by dorukozturk** [comment]
@dementiev Thanks for creating the issue. You should create an annotation using the buttons. The error is simply saying there are no polygons. 

![deepinscreenshot_select-area_20170908123417](https://user-images.githubusercontent.com/11761461/30221579-ca740cd2-9491-11e7-9f7a-8ff925b3a301.png)

**Comment by dementiev** [comment]
Got it, thanks!
