### ISSUE TITLE
Docker install not working out of the box

### ISSUE THREAD

**Issue by ahane** [OpenGeoscience/geonotebook#149]
I have built the container from the Dockerfile in the repository.
I am successfully running the notebook server and have the `'M <geonotebook.kernel.Geonotebook>` object in my namespace. But `M._remote` property is `None`, therefore all methods fail with exceptions:

```
M.set_center(-120, 47, 8)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-0ccb2cfb446e> in <module>()
----> 1 M.set_center(-120, 47, 8)

/usr/local/lib/python2.7/dist-packages/geonotebook/kernel.pyc in set_center(self, x, y, z)
    358             self.x, self.y, self.z = result
    359 
--> 360         return self._remote.set_center(x, y, z)\
    361             .then(_set_center, self.rpc_error).catch(self.callback_error)
    362 

AttributeError: 'NoneType' object has no attribute 'set_center'
```

The map screen that is visible in the gif in the README is also never displayed.

Any pointers? Thanks :)

**Comment by danlamanna** [comment]
I'm unable to reproduce this issue building off of master (34e88074) and
following the instructions mentioned here:
https://github.com/OpenGeoscience/geonotebook/tree/master/devops/docker.

One thing you can try is using the pre-built Docker image from Dockerhub
which is known to be working:

docker run -p 8888:8888 -it -v /path/to/your/notebooks:/notebooks --rm
geonotebook/geonotebook

replacing the /path/to/your/notebooks with the "notebooks" directory in
a clean GeoNotebook checkout just to be safe.

**Comment by ahane** [comment]
The pre-built image worked indeed. Thank you.
