### ISSUE TITLE
no access to data dir

### ISSUE THREAD

**Issue by dementiev** [OpenGeoscience/geonotebook#154]
Geonotebook is launched with docker command:
docker run -p 8888:8888 \
  -v /Users/XXX/Documents/notebooks/geonotebook:/notebooks  \
  -v /Users/XXX/Documents/gisdata:/data -it --rm geonotebook

In notebook then I can't access file stored in data dir:
os.access('/Users/XXX/Documents/gisdata/filename.tif', os.R_OK) => returns false

Any suggestions?

**Comment by danlamanna** [comment]
It seems like you're mounting gisdata at /data, so your os.access line
should be:

os.access('/data/filename.tif', os.R_OK)

**Comment by dementiev** [comment]
@danlamanna you are right, thank you.
