### ISSUE TITLE
Ktile map does not show up with the basemap

### ISSUE THREAD

**Issue by drzhouq** [OpenGeoscience/geonotebook#157]
tried to follow the 02_raster_data notebook provided. The tile generated by ktile does not show up with the basemap. It seems the ktile uses x/y/z, and the base map use z/x/y.  Will that be the issue?

**Comment by aashish24** [comment]
@drzhouq that shouldn't be the case. have you tried using the other basemap? You can change the basemap in this config file. https://github.com/OpenGeoscience/geonotebook/blob/master/config/geonotebook.ini

**Comment by drzhouq** [comment]
Thanks for your reply, @aashish24. Base map shows up correctly, and I know the ktile generated tiles are also fine. The only difference is that base map tiles are in the x/y/z pattern, and the ktile is in z/x/y.  When a ktile generated layer is added to the map, it uses the "osm" type (the same type of the base map). That's why I suspect why the ktile tiles don't show up in the correct place.

**Comment by asmith26** [comment]
I am also not able to display the raster on the map in the *02_Raster_data.ipynb**

I was able to do this by simply pressing lots of Shift-Enter a couple of weeks ago - given there have not been any recent code changes I thought this may have been a broswer update problem, but trying the example notebook on Firefox, Chrome and Chromium nothing is displayed?

**Comment by aashish24** [comment]
@asmith26 sorry to hear this. Since most of us are out it may take us few days to look into it. Are yo using master as of today?

**Comment by asmith26** [comment]
Thanks for your reply, @aashish24. 

I'm using the docker image, and mounting the git repo (cloned today) with:

`docker run -p 8888:8888 -it -v /path/to/your/notebooks:/notebooks --rm
geonotebook/geonotebook`

**Comment by asmith26** [comment]
I can now display all rasters in the example notebooks.

Not sure why it works now (I did literally nothing - possibly a browser update??)

Thanks again
