### ISSUE TITLE
Annotations buttons not working

### ISSUE THREAD

**Issue by davv-deimos** [OpenGeoscience/geonotebook#161]
Hello guys.

I'm using the latest image from docker hub and for some reason the annotations' buttons don't to be working.

I'm using Firefox 57 on Linux with all of my add-ons turned off.

Can someone help me on this. Thank you in advance!

**Comment by jbeezley** [comment]
I just tried on the latest image
```
$ docker pull geonotebook/geonotebook
latest: Pulling from geonotebook/geonotebook
Digest: sha256:b3b973ad44d45b7c01c6dfe9d4aa48fb0f24edb82dcd1a12c109d77c1e69b1b3
Status: Image is up to date for geonotebook/geonotebook:latest
```
Using Firefox 58 on Linux the annotations interactions work for me (they draw correctly and are accessible from the python kernel).  Could you check to see if there are any errors printed in the javascript console?

**Comment by davv-deimos** [comment]
could you please tell me how do I open that console?

**Comment by jbeezley** [comment]
You can open it from the "Web Developer" menu item, or just by pressing "Ctrl-Shift-i".  Just see if it prints anything out when trying to draw an annotation.  That information would be helpful.  Thanks.

**Comment by davv-deimos** [comment]
Thank you!

Is this it? 
![imagem](https://user-images.githubusercontent.com/33056229/36855368-235278d6-1d6b-11e8-9cf9-74aa64572688.png)

**Comment by jbeezley** [comment]
Thanks, that's helpful.  It looks like webgl is failing.  I'm not sure if our canvas fallback works for annotations, but I'll check.  I might be able to provide a work around.  Let me explore it a bit.

**Comment by davv-deimos** [comment]
so that means the problem is not on my side?

**Comment by jbeezley** [comment]
Yes and no.  It's likely it would work if webgl was supported on your browser.  You could try going to https://get.webgl.org/, I think that site provides some tips on how to fix it.  On our side though, fall-back to a non-webgl renderer would be a nice feature, so I'll try to get that working.

**Comment by davv-deimos** [comment]
So, I followed this [guide](https://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser) and forced webgl by making `webgl.force-enabled = True`, but it still doesn't work and I get this console output

![imagem](https://user-images.githubusercontent.com/33056229/36860980-b1dce14a-1d7a-11e8-94ed-f22c4673aae7.png)

**Comment by davv-deimos** [comment]
I just tried Google Chrome and the problem persists.
![imagem](https://user-images.githubusercontent.com/33056229/36897759-c5d3c002-1e0f-11e8-979c-eb4ad6237dca.png)
I though this might help you :)

**Comment by jbeezley** [comment]
I pushed a branch that might fix your issue.  Could you test out the tag `geonotebook/geonotebook:fix-webgl-fallback` and see if that works for you?

```
docker run -it -v $PWD/notebooks:/notebooks -p 8888:8888 geonotebook/geonotebook:fix-webgl-fallback
```

**Comment by davv-deimos** [comment]
For now it seems to be working, on both Firefox and Chrome. I'm going to keep following the tutorial/examples. 

Than you very much for your help!
