### ISSUE TITLE
Cannot add VRT raster layer

### ISSUE THREAD

**Issue by naterubin** [OpenGeoscience/geonotebook#166]
I am trying to add a layer using a RasterData object initialized with a VRT image.

```
vrt = RasterData("test.vrt")
M.add_layer(vrt)
```

The layer does not appear on the map and the Jupyter server throws this error:

```
    RuntimeError: `/test.vrt' does not exist in the file system,
    and is not recognised as a supported dataset name.
```
Am I correct in assuming that GeoNotebook supports raster layers from VRTs and if so, have I correctly gone about adding the layer?

**Comment by danlamanna** [comment]
Are you using the docker setup? A common issue with that is improperly mounting local data.

**Comment by naterubin** [comment]
Ah, that would make sense. I am using the docker setup, I'm running the image as such:

```
docker run -p 8888:8888 -v $(pwd):/notebooks -it --rm geonotebook/geonotebook
```

**Comment by dorukozturk** [comment]
You can add another volume with your data like "-v /some/directory/with/vrts/and/tiffs:/somedata". Make sure your vrt points to a path that exists in the container.

**Comment by naterubin** [comment]
This was in fact an issue with absolute paths. Thank you for your help.
