### ISSUE TITLE
New connection error

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geonotebook#21]
ConnectionError                           Traceback (most recent call last)
<ipython-input-10-ddf76be5b536> in <module>()
----> 1 M.add_layer(rdc[:,[1,2,3]], 'NBAR', opacity=0.8)

/home/chaudhary/tools/geonotebook/geonotebook/geonotebook/kernel.pyc in add_layer(self, data, name, vis_url, layer_type, **kwargs)
    347                 RuntimeError("RasterDataCollection layers require a 'name'")
    348 
--> 349             layer = TimeSeriesLayer(name, self._remote, data=data, vis_url=vis_url, **kwargs)
    350 
    351         else:

/home/chaudhary/tools/geonotebook/geonotebook/geonotebook/layers.pyc in __init__(self, name, remote, data, vis_url, **kwargs)
     88         if self.vis_url is None:
     89             self.vis_url = self.config.vis_server.ingest(
---> 90                 self.current, name=self.current.name)
     91 
     92         self.vis_server_kwargs = kwargs

/home/chaudhary/tools/geonotebook/geonotebook/geonotebook/vis/geoserver/geoserver.pyc in ingest(self, data, name)
    153 
    154         r = self.c.post("/workspaces.json",
--> 155                         json={'workspace': {'name': self.workspace}})
    156 
    157         if r.status_code != 201:

/home/chaudhary/tools/geonotebook/geonotebook/geonotebook/vis/geoserver/geoserver.pyc in post(self, *args, **kwargs)
     23 
     24     def post(self, *args, **kwargs):
---> 25         return self._proxy(requests.post, *args, **kwargs)
     26 
     27     def delete(self, *args, **kwargs):

/home/chaudhary/tools/geonotebook/geonotebook/geonotebook/vis/geoserver/geoserver.pyc in _proxy(self, method, uri, *args, **kwargs)
     14             return method(uri, *args, **kwargs)
     15         else:
---> 16             return method(self.base_url + uri, *args, **kwargs)
     17 
     18     def get(self, *args, **kwargs):

/home/chaudhary/.virtualenvs/geonotebook/local/lib/python2.7/site-packages/requests/api.pyc in post(url, data, json, **kwargs)
    108     """
    109 
--> 110     return request('post', url, data=data, json=json, **kwargs)
    111 
    112 

/home/chaudhary/.virtualenvs/geonotebook/local/lib/python2.7/site-packages/requests/api.pyc in request(method, url, **kwargs)
     54     # cases, and look like a memory leak in others.
     55     with sessions.Session() as session:
---> 56         return session.request(method=method, url=url, **kwargs)
     57 
     58 

/home/chaudhary/.virtualenvs/geonotebook/local/lib/python2.7/site-packages/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    473         }
    474         send_kwargs.update(settings)
--> 475         resp = self.send(prep, **send_kwargs)
    476 
    477         return resp

/home/chaudhary/.virtualenvs/geonotebook/local/lib/python2.7/site-packages/requests/sessions.pyc in send(self, request, **kwargs)
    594 
    595         # Send the request
--> 596         r = adapter.send(request, **kwargs)
    597 
    598         # Total elapsed time of the request (approximately)

/home/chaudhary/.virtualenvs/geonotebook/local/lib/python2.7/site-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    485                 raise ProxyError(e, request=request)
    486 
--> 487             raise ConnectionError(e, request=request)
    488 
    489         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /geoserver/rest/workspaces.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd370fcaa90>: Failed to establish a new connection: [Errno 111] Connection refused',))

Things were going well until I hit this issue.

**Comment by aashish24** [comment]
I guess I need to run the geoserver manually?

**Comment by dorukozturk** [comment]
@aashish24 Yes, you need to do a "vagrant up" in the geoserver directory.

**Comment by kotfic** [comment]
@aashish24 Were you able to resolve this?

**Comment by aashish24** [comment]
Yes, thanks.
