### ISSUE TITLE
Set up travis for running python unittests

### ISSUE THREAD

**Issue by kotfic** [OpenGeoscience/geonotebook#33]

**Comment by danlamanna** [comment]
We should add a `flake8.cfg` to the mix, there are a lot of small things like unused imports lying around.

**Comment by dorukozturk** [comment]
If I can compile GDAL without problems I would be a volunteer to work on this.

**Comment by danlamanna** [comment]
Couple more thoughts:
- Tests need to run against multiple version of python (at least 2.7 and 3.5), might make sense to use tox
- Might make sense to use CircleCI instead (SSH access might be necessary with the in depth setup we have)

**Comment by kotfic** [comment]
@dorukozturk I agree with @danlamanna completely.  :+1: for circleci :+1: for tox.  I know you've already put some work into getting travis up and running but I think dan makes a compelling point about ssh access and GDAL issues.  Looking through the circleci docs it looks like an all around better experience.

**Comment by aashish24** [comment]
@kotfic should we close this?
