### ISSUE TITLE
Babel breaks automatic jsonrpc parsing

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/geonotebook#54]
Currently, the babel [parameters transform](https://babeljs.io/docs/plugins/transform-es2015-parameters/) is enabled through the `ES2015` preset.  This does the following:
```javascript
> fn = function (a=0) {}
[Function: fn]
> fn.toString()
'function () {\n  var a = arguments[0] === undefined ? 0 : arguments[0];\n}'
```
This breaks the optional argument parsing that we do.  We can disable the babel transform (or babel entirely), but that means it will be [impossible to support](http://caniuse.com/#feat=rest-parameters):
* IE (any version)
* Safari < 10 (9.1 is still supported by Apple)
* PhantomJS (any version)
* Node < 6 (without `--harmony`)

It does look like PhantomJS support for ES6 is coming, but it hasn't landed yet.  I know decided not to support older browsers, but this would make that decision permanent and unavoidable, so I wanted to make the consequences clear before disabling babel on my own.

**Comment by kotfic** [comment]
This is unfortunate,  but for now I think it is acceptable to drop support for these browser.  I am wondering if you have any thoughts on a way to track information like this.  It would be nice to have a list of browsers,  python versions (other things?) that we _know_ we can't support and references to issues.  Maybe a wiki page? For now lets leave the issue open,  we may want to start marking issues like this with 'wontfix'  or 'low priority' or something?

**Comment by jbeezley** [comment]
After thinking about it a bit, I think we do have a path forward using a custom babel transform to support older browsers.  It's a little ugly, but it would amount to forking [es2015-parameters](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-parameters) and modifying the `default.js` transpilation to include some sort of sentinel indicating the optional parameters present in the original function.

I'm in the process of building out the javascript testing in which we can test against Chrome and Firefox in CircleCI.  The rpcjson function parsing is a good candidate for unit testing.

**Comment by kotfic** [comment]
Great.  For now i think we can leave off forking es2015-paramaters and just test the function as is.

**Comment by kotfic** [comment]
@jbeezley Is this still an open issue?

**Comment by jbeezley** [comment]
The title is still a true statement, but we have stopped transpiling, so I think we can close.
