### ISSUE TITLE
Find/develop better solution for python async calls to map

### ISSUE THREAD

**Issue by kotfic** [OpenGeoscience/geonotebook#6]
Currently [ReplyCallback](https://github.com/OpenGeoscience/geonotebook/blob/master/geonotebook/kernel.py#L23) is used to manage JSONRPC replies on the [Remote](https://github.com/OpenGeoscience/geonotebook/blob/master/geonotebook/kernel.py#L69) object. Given that these are a poor man's [promise](https://en.wikipedia.org/wiki/Futures_and_promises) it would be nice to use an actual implementation that supports chaining promises etc. Given that Tornado already implements  [Futures](http://www.tornadoweb.org/en/stable/concurrent.html) it might be nice to start looking there - its possible a fairly large amount of the mechanics developed in kernel.py can be replaced with built in tornado features. An assessment of that would also be nice.

**Comment by danlamanna** [comment]
Fixed via #18
