### ISSUE TITLE
Map displaying behind notebook cells

### ISSUE THREAD

**Issue by robintw** [OpenGeoscience/geonotebook#70]
I've just come across this project and it looks like it'd be so useful to me. I've installed following the installation instructions, but when I run the notebooks I get the map appearing behind the notebook itself. It's kinda hard to explain, but the attached image should show what I mean.

Do you have any idea what might be going on here?

<img width="1185" alt="screen shot 2017-01-14 at 18 44 40" src="https://cloud.githubusercontent.com/assets/296686/21957251/7506350c-da8a-11e6-9bbd-970576b5cca0.png">

**Comment by jbeezley** [comment]
It looks like the CSS isn't getting applied correctly.  What OS and browser are you using?

**Comment by jbeezley** [comment]
`npm --version` and `node --version` would be helpful to know as well.

**Comment by robintw** [comment]
I'm using OS X 10.10.5 and Chrome Version 55.0.2883.95 (64-bit), with:

npm v3.8.9
node v6.2.0

I've tried it in Safari too and get the same issue.

Thanks for looking into this with me.

**Comment by jbeezley** [comment]
Happy to help.

I can reproduce that behavior by deleting the css file built by geonotebook, so I suspect the issue is that it is not being built or copied to the correct place.  If that is the case, you should be getting a console message in developer tools (Cmd-Option-i) that says `http://localhost:8888/nbextensions/geonotebook/styles.css` could not be loaded.  This file should be built to `geonotebook/static` and copied into your python virtualenv under `share/jupyter/nbextensions/geonotebook` during the install.

You might try reinstalling with the verbose option (`pip install -v .`) to see if there is some error raised by the client asset build.

**Comment by robintw** [comment]
Interesting I don't have that error in the devtools console, but I do have some other errors - see below for the whole output of the console:

```
loaded custom.js
default.js:48 Default extension for cell metadata editing loaded.
rawcell.js:82 Raw Cell Format toolbar preset loaded.
slideshow.js:43 Slideshow extension for metadata editing loaded.
menubar.js:240 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
MenuBar.bind_events @ menubar.js:240
events.js:31 Exception in event handler for app_initialized.NotebookApp TypeError: IPython.load_extensions is not a function
    at Events.<anonymous> (custom.js?v=20170116144853:84)
    at Events.dispatch (jquery.min.js:5)
    at Events.y.handle (jquery.min.js:5)
    at Object.trigger (jquery.min.js:5)
    at Events.<anonymous> (jquery.min.js:5)
    at Function.each (jquery.min.js:4)
    at init.each (jquery.min.js:4)
    at init.trigger (jquery.min.js:5)
    at init.events.trigger (events.js:29)
    at main.js:157 Arguments[1]
events.trigger @ events.js:31
utils.js:59 load_extensions Arguments[7]0: "nbextension-scratchpad/main"1: "jupyter-js-widgets/extension"2: "publishing/gist_it/main"3: "livereveal/main"4: "usability/dragdrop/main"5: "geonotebook/index"6: "qtconsole-button"callee: (...)get callee: ThrowTypeError()set callee: ThrowTypeError()caller: (...)get caller: ThrowTypeError()set caller: ThrowTypeError()length: 7Symbol(Symbol.iterator): values()__proto__: Object
session.js:54 Session: kernel_created (6e16a0ab-9133-4a7c-a6a6-1fbab1fc34a1)
kernel.js:453 Starting WebSockets: ws://localhost:8889/api/kernels/b6875b01-6531-47e6-8fe2-b96a383c6c87
utils.js:36 Loading extension: livereveal/main
utils.js:36 Loading extension: publishing/gist_it/main
utils.js:36 Loading extension: nbextension-scratchpad/main
main.js?v=20170116144853:106 Setting up scratchpad
utils.js:36 Loading extension: usability/dragdrop/main
utils.js:36 Loading extension: qtconsole-button
utils.js:36 Loading extension: jupyter-js-widgets/extension
extension.js:88 loaded widgets
utils.js:36 Loading extension: geonotebook/index
3main.js:164 accessing "actions" on the global IPython/Jupyter is not recommended. Pass it to your objects contructors at creation time
get @ main.js:164
extension.js:25 loaded geonotebook
kernel.js:100 Kernel: kernel_connected (b6875b01-6531-47e6-8fe2-b96a383c6c87)
kernel.js:100 Kernel: kernel_ready (b6875b01-6531-47e6-8fe2-b96a383c6c87)
2manager-base.js:195 Widget backend and frontend versions are compatible
```

I've checked and `style.css` has been copied to the right place and is exactly the same as the `style.css` in the `geonotebook/static` directory.

**Comment by jbeezley** [comment]
Okay, that helps.  It's probably a conflict with one of the other notebook extensions you have installed.  I'll do some experimenting to see what's causing it.  Thanks for letting us know.

**Comment by kotfic** [comment]
@robintw could you show us the output of ```jupyter nbextension list``` and ```jupyter serverextension list```?  Thanks!

**Comment by robintw** [comment]
Sure:

```
Known nbextensions:
  config dir: /Users/robin/.jupyter/nbconfig
    notebook section
      nbextension-scratchpad/main  enabled 
      - Validating: OK
      publishing/gist_it/main  enabled 
      - Validating: OK
      usability/dragdrop/main  enabled 
      - Validating: OK
      qtconsole-button  enabled 
      - Validating: OK
      livereveal/main  enabled 
      - Validating: OK
  config dir: /Users/robin/anaconda3/envs/py2geonotebook/etc/jupyter/nbconfig
    notebook section
      geonotebook/index  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

and

```
config dir: /Users/robin/.jupyter
    jupyterlab  enabled 
    - Validating...
Error loading server extension jupyterlab
      X is jupyterlab importable?
    nbextensions  enabled 
    - Validating...
Error loading server extension nbextensions
      X is nbextensions importable?
config dir: /Users/robin/anaconda3/envs/py2geonotebook/etc/jupyter
    geonotebook  enabled 
    - Validating...
      geonotebook  OK
```

**Comment by kotfic** [comment]
I would recommend disabling all other extensions (for now),  then reinstalling geonotebook (pip install -U .) and seeing if you still see this behavior.  I can't seem to find an option in ```jupyter notebook --help``` that lets you do this at run time so you may have to do jupyter nbextesion disable <package>  for each item.  We haven't done a lot of testing with other extensions,  so I'm not sure how their css may be affecting what you're seeing.

**Comment by kotfic** [comment]
@robintw if you want to jump into the [gitter](https://gitter.im/OpenGeoscience/geonotebook) channel i just set up  we can also help you troubleshoot

**Comment by jbeezley** [comment]
Okay, I managed to track down the issue here (probably).  What I'm seeing is that server extensions are not loading when there are multiple config directories.  To be precise, [this function](https://github.com/OpenGeoscience/geonotebook/blob/master/geonotebook/__init__.py#L59) is not executed when a different config directory is listed first.  This is likely a jupyter notebook bug.  I was able to fix the immediate issue of our custom template not getting rendered by removing the user config directory at `~/.jupyter` and installing new extensions with the flag `--sys-prefix`, à la
```
jupyter nbextension enable --sys-prefix <extension>
```
or
```
jupyter nbextensions_configurator enable --sys-prefix
```

On a side note, we probably shouldn't be automatically installing the geonotebook extension in `setup.py`.  Looking at `nbextensions_configurator` and the install instructions for many packages, users are instructed to use `--user`.  I think its better to stay consistent with the rest of the community than to automagically enable the plugin during installation.

**Comment by robintw** [comment]
Thanks - renaming the user config directory and then installing with `--sys-prefix` makes it all work for me. It definitely sounds like a jupyter bug - are you happy to report this upstream?

Interestingly, I don't have the command `jupyter nbextensions_configurator` on my system. Not sure whether that is to be expected or not, but anyway I've now got it working (albeit without my other extensions).

Thanks again!

**Comment by kotfic** [comment]
@jbeezley yeah,  the hope was to make this as easy as ```pip install geonotebook```  but if this is already demonstrating issues then I think we should probably just pull it out. I will file an issue

**Comment by jbeezley** [comment]
Thanks for confirming the fix.  I reported upstream here: https://github.com/jupyter/notebook/issues/2063

I tried a few extensions (installed into the virtualenv rather than `--user`) with geonotebook enabled, and they seemed to work.  It is likely we will run into compatibility issues with specific extensions that we will have to deal with individually.  Let us know if you have any more problems.

**Comment by jepeloa** [comment]
hello, i'm trying to install geonotebook, in the last step when executed pip install . 
appears this error, npm as installed an its working correctly. Thanks

Processing c:\users\user\desktop\geonotebook
    Complete output from command python setup.py egg_info:
    setup.py entered
    $PATH=C:\Users\User\Envs\geonotebook\Scripts;C:\Program Files (x86)\Git\cmd;c:\mingw\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\LLVM\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\PuTTY\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\\Bin\;C:\Users\User\AppData\Local\atom\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Roaming\npm;C:\Users\User\AppData\Local\Pandoc\;C:\Program Files\Microsoft VS Code\bin
    running egg_info
    running jsdeps
    `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
    rebuilding js and css failed
    missing files: ['c:\\users\\user\\appdata\\local\\temp\\pip-lcc29t-build\\geonotebook\\static\\index.js', 'c:\\users\\user\\appdata\\local\\temp\\pip-lcc29t-build\\geonotebook\\static\\styles.css']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\user\appdata\local\temp\pip-lcc29t-build\setup.py", line 314, in <module>
        "ktile = geonotebook.vis.ktile:Ktile"
      File "c:\users\user\envs\geonotebook\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\python27\Lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\Lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\Lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\user\appdata\local\temp\pip-lcc29t-build\setup.py", line 117, in run
        raise e
    ValueError: Missing file: c:\users\user\appdata\local\temp\pip-lcc29t-build\geonotebook\static\index.js
    npm is required to build a development version
