### ISSUE TITLE
Set up read the docs

### ISSUE THREAD

**Issue by kotfic** [OpenGeoscience/geonotebook#77]
@danlamanna lets coordinate on content/headings

**Comment by aashish24** [comment]
@kotfic can three of us meet on this? I have some ideas based on my discussions with few folks at the ESIP.

**Comment by danlamanna** [comment]
@dorukozturk Also mentioned doing a pass on the notebooks to ensure that the notebooks involving data downloads work out of the box.

Additionally, look into how to use proper docblocks for integrating with the notebooks built in documentation viewer.
