### ISSUE TITLE
Basemap does not change on refresh

### ISSUE THREAD

**Issue by kotfic** [OpenGeoscience/geonotebook#83]
If I start a kernel with a certain basemap,  then change the basemap in the geonotebook.ini config,  then refresh - the new basemap is not displayed.  This has to do with the basemap only being set on initialization and will require a refactor to fix. 

@jbeezley FYI

**Comment by jbeezley** [comment]
I think this is because the config file is only read when the server starts.  IMO restarting the server should be necessary for this kind of a change.  If we want base maps to be changeable on the fly, I would suggest that we move the option from the config file to a property on the `M` class.

**Comment by kotfic** [comment]
I'll buy that.
